Document usage with a Dockerfile
sclorg/nginx-container pull request #131
Opened 2020-11-11 08:48 UTC by hhorak

This PR depends on #128 that needs to be merged first.

This adds the following enhancements:

- Dockerfile examples for a variant that uses s2i scripts and a variant without s2i scripts
- Documentation enhancement that describes how the image can be used using a Dockerfile
- A test for the example Dockerfiles

This is a similar pull-request as sclorg/httpd-container#99., sclorg/nodejs-container#247 and sclorg/perl-container#192

To see the formatted README.md, see https://github.com/hhorak/nginx-container/blob/doc-dockerfile/1.18/README.md and it is also visible in the catalog, which will be the most important view: https://catalog.redhat.com/software/containers/detail/5f521a6f9dd2d5ca7158e5dc

2020-12-14 18:14 UTC, hhorak commented
[test]

2020-12-15 07:26 UTC, hhorak commented
[test]

2020-12-15 10:31 UTC, phracek requested changes
I have reviewed this PR. Thanks for it. One question. Otherwise LGTM.

2020-12-15 13:11 UTC, hhorak commented
[test]

2020-12-15 13:12 UTC, hhorak commented
> I have reviewed this PR. Thanks for it. One question. Otherwise LGTM.

I'm happy to answer, but can't find what the question is :)

2020-12-15 13:26 UTC, phracek requested changes

2020-12-15 13:37 UTC, pkubatrh commented on 1.16/s2i/bin/usage
> +  oc new-app nginx:${NGINX_VERSION}~https://github.com/sclorg/nginx-container.git --context-dir=${NGINX_VERSION}/test/test-app/
I expect the stream used here will be named `nginx:1.16`, the line in the README you link to uses the image name, which is indeed `nginx-116`

2020-12-15 13:38 UTC, pkubatrh commented on 1.16/s2i/bin/usage
> +  oc new-app nginx:${NGINX_VERSION}~https://github.com/sclorg/nginx-container.git --context-dir=${NGINX_VERSION}/test/test-app/
https://github.com/sclorg/nginx-container/blob/master/imagestreams/nginx-rhel.json#L129

2020-12-15 13:44 UTC, phracek commented on 1.16/s2i/bin/usage
> +  oc new-app nginx:${NGINX_VERSION}~https://github.com/sclorg/nginx-container.git --context-dir=${NGINX_VERSION}/test/test-app/
Aha, ok. The name is taken from OpenShift template.

2020-12-15 13:45 UTC, phracek approved these changes
LGTM

2020-12-15 13:45 UTC, phracek commented
[test-openshift]

2020-12-15 16:22 UTC, hhorak commented
The OpenShift tests are not relevant here, as this PR only adds Dockerfile examples and fixes documentation. Merging despite the OpenShift tests fail, it seems they fail from some problem with the cluster anyway.

2020-12-15 16:22 UTC, merged